global:
  scrape_interval: 5s
  external_labels:
    monitor: 'node'

scrape_configs:
  - job_name: 'status-page-app'
    static_configs:
      - targets: ['status-page:8001']  
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']  

